networks:
  knights-challenge:
    driver: bridge
services:
  db:
    image: mongo
    container_name: db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}    
    ports:
      - "${DB_PORT}:27017"
    networks:
      - knights-challenge
    env_file:
      - .env
  app: 
    container_name: app
    build:
      context: .
      target: api
    ports:
      - ${API_PORT}:${API_PORT}
    command: yarn start:backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - knights-challenge
