networks:
  default:
    name: 'knights-challenge'
services:
  db:
    image: mongo
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:27017"