networks:
  knights-challenge:
    driver: bridge
services:
  db:
    build:
      context: .
      target: mongo
    container_name: db
    ports:
      - "${DB_PORT}:27017"
    networks:
      - knights-challenge
