networks:
  default:
    name: 'knights-challenge'
services:
  db:
    build:
      context: .
      target: mongo
    container_name: db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--setParameter", "enableLocalhostAuthBypass=true"]    
    ports:
      - "${DB_PORT}:27017"